name: PR
on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  cla:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          name: itaysk/cla
          fetch-depth: "1"
      - name: CLA check
        run: |
          CLA_REPO=cla
          CLA_REPO_ORG=itaysk
          MESSAGE="This repository requires contributors to sign a Contributor License Agreement (CLA). For info and instructions, please see http://google.com"
          #git clone --depth 1 "https://github.com/$CLA_ORG/$CLA_REPO.git" "$CLA_REPO" && cd "$CLA_REPO"
          cd cla && ls
          echo "Checking CLA for: $GITHUB_ACTOR"
          if ! grep "^$GITHUB_ACTOR$" db/*
          then
            echo "$MESSAGE"
            exit 1
          fi
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo "hi" > artifact
