name: PR
on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  cla:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          name: itaysk/cla
          fetch-depth: "1"
      - name: CLA check
        run: |
          MESSAGE="This repository requires contributors to sign a Contributor License Agreement (CLA). For info and instructions, please see http://google.com"
          echo "Checking CLA for: $GITHUB_ACTOR"
          gh auth login --with-token <<<'${{ secrets.GITHUB_TOKEN }}'
          PR=$(jq '.number' "$GITHUB_EVENT_PATH")
          gh pr comment "$PR" --body "$MESSAGE"
          if ! grep "^$GITHUB_ACTOR$" db/*
          then
            gh pr comment --body "$MESSAGE"
            exit 1
          fi
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo "hi" > artifact
