name: PR
on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  cla:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          repository: itaysk/cla
          fetch-depth: "1"
      - name: check
        run: ls -l && grep "^$GITHUB_ACTOR$" db/*
      - name: notify
        if: ${{ failure() }}
        run: |
          set -e
          echo "CLA for $GITHUB_ACTOR not found"
          PR=$(jq '.number' "$GITHUB_EVENT_PATH")
          MESSAGE="This repository requires contributors to sign a Contributor License Agreement (CLA). For info and instructions, please see CONTRIBUTING.md"
          gh auth login --with-token <<<'${{ secrets.GITHUB_TOKEN }}'
          gh pr comment "$PR" --body "$MESSAGE"
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo "hi" > artifact
