name: PR
on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  cla:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          repository: itaysk/cla
          fetch-depth: "1"
      - name: check
        run: |
          USER=$(jq -r '.sender.login' "$GITHUB_EVENT_PATH")
          grep "^$USER$" db/*
      - name: notify
        if: ${{ failure() }}
        run: |
          PR=$(jq -r '.number' "$GITHUB_EVENT_PATH")
          MESSAGE="This repository requires contributors to sign a Contributor License Agreement (CLA). For info and instructions, please see CONTRIBUTING.md"
          gh auth login --with-token <<<'${{ secrets.GITHUB_TOKEN }}'
          gh pr comment "$PR" --body "$MESSAGE"
