name: PR
on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  cla:
    runs-on: ubuntu-latest
    steps:
      - run: |
          MESSAGE="This repository requires contributors to sign a Contributor License Agreement (CLA). For info and instructions, please see http://google.com"
          echo $GITHUB_ACTOR
          if ! grep "^$GITHUB_ACTOR$" "db/*"
          then
            echo "$MESSAGE"
            exit 1
          fi
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo "hi" > artifact
